### PR TITLE
Ekaterina/Project1

### PR DESCRIPTION
**Pull request by ekaterina392**
[Link to check-in or debrief if applicable](link to google doc goes here)

<h2>Summary</h2>
 
My project is an arcade game with a 3rd person player. The player has to deal with obstacles/enemies in order to reach the gateway for the given amount of time. For now, the basic features are moving and jumping.
The game still lacks some features like enemies, player collision with obstacles, and timing. The project is nearly 50 % complete.

<h2>Details</h2>

I have implemented player movements, sound, ground blocks/obstacles, and the background. I have decided to use all of these because it is a standard set of things that an arcade game of such type should include. I used the Mario game as an example.

<h2>Visuals</h2>

gif

<h2>How to Test</h2>

In order to play the game, you will need to use arrow keys to move and space to jump. There are some issues that appear when the player collides with the ground blocks. Specifically, the blocks are clinging to the player.

<h2>How to Review</h2>

I would like to have feedback on the graphics and the player animation.
In my project, I used camera-following, collision, player movement controller, animation, and sound.
I used textures for the background, ground blocks, obstacles (water/spikes), and the player.
The game looks like something between Mario and Sonic. It is made in a pixelated style and with classic arcade background music. It is supposed to be a fast-paced game. The player should feel the need to hurry up as in order to complete the level he will need to reach the exit on time.

### CODE REVIEW

**Review by jasonzli — COMMENTED** [review]
Original description is here, make sure to link it in the future if it needs that https://github.com/jli-systems-games/FA22-class-repo/pull/17

Looks mostly good! I would consider changing the name of your scene to something less generic.

**Comment by DinosaurPower** [comment]
Hi Ekaterina!!
The project is A-MAZE-ING! I absolutely love the graphics, motion and camera follow. You found super nice assets to use, and the code looks quite clean.
Few of the patches I would offer include:
1) Music: please, just a little less loud🙏 I really appreciate thematical music and it's a nice soundtrack, but it was quite loud and sudden
2) Endgame: the prototype is super fun to try, but it would be really nice to have some sort of win state
Also, the animation is slick with extended ck for extra smoothness. It works properly and looks quite professional. I love it! Looking forward seeing final iteration of project!!

**Review by redmoe — CHANGES_REQUESTED** [review]
Looks good! Request changes:

- [ ] Add namespace to Enemy, Playerlife, Wall scripts

**Comment by redmoe** [comment]
I'd recommend this tutorial for creating titlescreen/win/lose screens:
[Title tutorial](https://www.youtube.com/watch?v=BjEqZfK15Ws)

**Comment by Hectorgamecreator** [comment]
Your loading screen is phenomenal, and your animated player is amazing! I did have difficulties trying to get over a certain point of the game when you need blocks to pass through it.  I think having the player have one life is a challenge, but it is interesting to have a health bar and see if the player can live longer than dying instantly.

**Pull request merged**
